### ISSUE TITLE
Lineage of observations 

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#24] opened 2019-09-27 17:18 UTC
Need for the possibility to relate two observations because one is derived from the other (lineage). 

Example: 
Observation 1: a series of ground water levels at several locations 
Observation 2: a model of a ground water body, which is derived from the water level measurements.

Source: http://ogc.standardstracker.org/show_request.cgi?id=612

**Comment by dr-shorthair** [comment] 2019-09-29 02:02
Inputs to an act of observation (estimation, computation etc) are described as part of the observation procedure.

**Comment by KathiSchleidt** [comment] 2019-09-29 17:56
@dr-shorthair To my memory, there's a lack of clarity around observation chaining. At present, we have relatedObservation, but this lacks semantic detail on how these observations are related.
As far as I understand SOSA/SSN, this would be linked to the procedure via ssn:hasInputs, would the sosa:Result of one sosa:Observation then serve as the ssn:Input to the next? Is this correct?
Also, do you have an example illustrating this?

**Comment by dr-shorthair** [comment] 2019-10-01 20:14
Yes - I think that is the pattern. 
But indeed, it has not been worked out or tested in detail. 
As with all things RDF the open-world-assumption means that you can elaborate the RDF as you want. 
Of course for ISO you want to tie it down more so I think that is work that has to be done. But the key point is that it belongs as part of the procedure description.

**Comment by soreslaszlo** [comment] 2019-10-30 13:50
Hi All,
Kathi has invited me to join this conversation. I tried modelling process chains for geophysical data many times. 

I completely agree that process chains on the lowest level should be defined by using process/hasInput (and hasOutput) links as in SOSA.
It would be nice to have these attributes ( hasInput: Any [0..*], hasOutput: Any [0..1] ) in O&M as well. Having more than one output may lead to confusion.

On the highest level chaining SamplingFeatures proved to be useful to me. ( SamplingFeatureComplex, role='uses' or 'usedFor' ) e.g.: waterLevelMeasurement -> usedFor -> waterLevelModel 
where both waterLevelModel and waterLevelMeasurement are SpatialSamplingFeatures.

![procChainObs](https://user-images.githubusercontent.com/57181802/67863641-90e79000-fb24-11e9-833a-0adaff24d3b4.png)

**Comment by dr-shorthair** [comment] 2019-10-31 07:49
Not sure this is quite right. I think you are mixing meta-levels

The individual `Process` is a re-usable thing. It might be the object of many `usedProcedure` relations. If you specify inputs and outputs they should be types or classes, not individuals. 

OTOH - the individual `Observation` is a one-off thing, whose `result` is an individual. The type of that individual result should be consistent with the output of the procedure. 

The inidividual result is directly associated only with the individual `Observation`. 

![image](https://user-images.githubusercontent.com/608303/67928299-c8cb0200-fc0e-11e9-8e5c-e13a1e6c6451.png)

**Comment by soreslaszlo** [comment] 2019-10-31 10:48
True! With Process the chain can be described on meta level. 
Individual results must be linked to Observation. Output is clearly the result, inputs can be simply defined through relatedObservations e.g. having role='previous'.
May be like this?

OBS1:
<om:OM_Observation gml:id="OBS1" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:om="http://www.opengis.net/om/2.0" xmlns:sam="http://www.opengis.net/sampling/2.0" xmlns:sams="http://www.opengis.net/samplingSpatial/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.geosciml.org/GeoSciML/3.0 http://www.geosciml.org/schemas/geosciml/3.0/geosciml.xsd">
   <om:relatedObservation>
      <om:ObservationContext>
         <om:role xlink:href="next"/>
         <om:relatedObservation xlink:href="OBS2" xlink:title="next observation"/>
      </om:ObservationContext>
   </om:relatedObservation>
   <om:phenomenonTime nilReason="unknown"/>
   <om:resultTime nilReason="unknown"/>
   <om:procedure xlink:href="PRC1" xlink:title="Groundwater Level Measurement"/>
   <om:observedProperty xlink:href="groundWaterLevel"/>
   <om:featureOfInterest xlink:href="SF1" xlink:title="SamplingFeature - MultiPointModel"/>
   <om:result xlink:href="MPCOV1"/>
</om:OM_Observation>

OBS2
<om:OM_Observation gml:id="OBS2" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:om="http://www.opengis.net/om/2.0" xmlns:sam="http://www.opengis.net/sampling/2.0" xmlns:sams="http://www.opengis.net/samplingSpatial/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.geosciml.org/GeoSciML/3.0 http://www.geosciml.org/schemas/geosciml/3.0/geosciml.xsd">
   <om:relatedObservation>
      <om:ObservationContext>
         <om:role xlink:href="previous"/>
         <om:relatedObservation xlink:href="OBS1" xlink:title="previous observation"/>
      </om:ObservationContext>
   </om:relatedObservation>
   <om:phenomenonTime nilReason="unknown"/>
   <om:resultTime nilReason="unknown"/>
   <om:procedure xlink:href="PRC2" xlink:title="GroundWaterSurfaceReconstruction" />
   <om:observedProperty xlink:href="groundWaterLevel"/>
   <om:featureOfInterest xlink:href="SF2" xlink:title="SamplingFeature - SurfaceModel"/>
   <om:result xlink:href="SRFCOV1"/>
</om:OM_Observation>

**Comment by hylkevds** [comment] 2019-10-31 12:09
One issue I see here is that these inputs all end up being a "relatedObservation". If a process has multiple inputs, how does one distinguish which relatedObservation was used for each of those inputs, and which relatedObservations are not inputs at all, but have some other relation?

In some cases this might be resolved by looking at the process of those related observations, but in some cases several related observations may have the same process, but still a different role in the process of our Observation in question.

**Comment by soreslaszlo** [comment] 2019-10-31 12:52
Can you give an example of several observations producing the same kind of results and having different role in the next processing step?

**Comment by hylkevds** [comment] 2019-10-31 13:09
At the moment I can't think of any where the difference actually matters. Either the observed property is different, or the process is different.

**Comment by dr-shorthair** [comment] 2019-11-01 03:01
I agree that an explicit chain is required, and there are certainly cases where different inputs of the same type are used in different ways - e.g. a mask expressed as a grid, and a gridded coverage. More modeling required. We probably don't need to solve it in detail for every case here, but do need to develop some patterns for how people would express the procedure and the observation in a processing chain.

**Comment by soreslaszlo** [comment] 2019-11-01 08:18
I think, if the same type of input is used in different ways, than more than one sub-processes are handled as one. Separating the sub-processes would solve the problem.
However, in practice it is not always helpful to show all details. In such cases the parallel sub-observations should also be handled as one. Observations and Processes must be parallel, meaning on the same level of complexity.

**Comment by fterpstra** [comment] 2019-11-20 13:20
I don't think you should try to standardize data lineage within O&M if you do want to describe data lineage have a look at https://en.wikipedia.org/wiki/PROV_(Provenance) a generic standard for data lineage

**Comment by KathiSchleidt** [comment] 2019-11-20 15:49
Alternatively, could/should we provide a recommendation on how to utilize ProvO for this? Does anybody have experience using these 2 models concurrently?
Lineage and processing chains are a recurring issue, so I'd feel bad to ignore it totally

**Comment by dr-shorthair** [comment] 2019-11-20 23:23
I've added an example of a _sample_ processing chain to the SSN-Extensions vocabulary - see https://raw.githack.com/w3c/sdw/simon-ssn-ext/proposals/ssn-extensions/index.html#sample-chains

**Comment by soreslaszlo** [comment] 2019-11-21 11:10
In O&M the equivalent of this pattern is chaining SamplingFeatures using SamplingFeatureComplex with role sosa:isSampleOf.
The water level example could be something like this:

![omExampleSL1](https://user-images.githubusercontent.com/57181802/69332808-b9f8cd80-0c57-11ea-8454-12832112f037.png)

Though getting water level data from boreholes is also a kind of sampling, it is more relevant to use prov:wasGeneratedBy instead of sosa:isSampleOf. The isUltimateSampleOf property is replaced by sampledFeature in O&M.

**Comment by dr-shorthair** [comment] 2019-11-21 19:43
> The isUltimateSampleOf property is replaced by sampledFeature in O&M.

Interesting. When we added `Sample` (noun, Entity) to SSN/SOSA the property `isSampleOf` was intended to do the work of `sampledFeature` so your interpretation here is slightly different. But maybe `sampledFeature` is a better name than `isUltimateSampleOf` (it brings in 'Feature' though drops 'ultimate').

**Comment by dr-shorthair** [comment] 2019-11-28 12:04
Updated the property name to match proposed - see https://w3c.github.io/sdw/proposals/ssn-extensions/#has-sampled-feature

**Comment by dr-shorthair** [comment] 2020-01-23 10:37
Now available at https://www.w3.org/TR/vocab-ssn-ext/#sosa:has Sampled Feature and illustrated at 
https://www.w3.org/TR/vocab-ssn-ext/#sample-chains RDF at https://github.com/w3c/sdw/blob/gh-pages/ssn-extensions/rdf/examples/Sample-chain-geology.ttl

**Closed** 2024-06-12 11:57 UTC
Labels: OGC CRP, Toulouse TC
